### ISSUE TITLE
Can the YISP interpreter be ported to atom?

### ISSUE THREAD

**Issue by thomasbaku** [rollinsbaird/YISP#1]
So I saw that YISP is created for VS Code and that awesome. I have been meaning to make the switch at some point, but for the time being I am still coding in the ide atom. Is there a way to load this YISP syntax highlighter in Atom? If so that would be great, but if not, it might be time for me to make the switch! 
Thanks

**Comment by rollinsbaird** [comment]
Absolutely! My project is under a MIT license, so feel free to port it & make a version for Atom. Or, since this extension is quickly growing in popularity, a project like https://github.com/atom-community/atom-vscode may do it for you soon!
